export const ExerciseData = [
  {
    id: 1,
    exerciseName: "Front squat",
    pb: "60kg",
    sets: 4,
    reps: 3,
    equipment: "BB",
    lastActivity: "20/02/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "1",
    day: "1",
    pbDate: "20/02/2023",
  },
  {
    id: 2,
    exerciseName: "Back squat",
    pb: "60kg",
    sets: 3,
    reps: 4,
    equipment: "BB",
    lastActivity: "02/03/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "2",
    day: "3",
    pbDate: "20/02/2023",
  },
  {
    id: 3,
    exerciseName: "Deadlift",
    pb: "60kg",
    sets: 4,
    reps: 5,
    equipment: "BB",
    lastActivity: "05/06/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "3",
    day: "2",
    pbDate: "20/02/2023",
  },
  {
    id: 4,
    exerciseName: "Clean and jerk",
    pb: "60kg",
    sets: 3,
    reps: 6,
    equipment: "BB",
    lastActivity: "15/09/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "3",
    day: "1",
    pbDate: "20/02/2023",
  },
  {
    id: 5,
    exerciseName: "Bicep curls",
    pb: "5kg",
    sets: 4,
    reps: 5,
    equipment: "DB",
    lastActivity: "25/01/2023",
    category: "Bodybuilding",
    bodyPart: "Upper",
    week: "4",
    day: "3",
    pbDate: "20/02/2023",
  },
  {
    id: 6,
    exerciseName: "Snatch pull",
    pb: "60kg",
    sets: 5,
    reps: 2,
    equipment: "BB",
    lastActivity: "07/08/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "4",
    day: "2",
    pbDate: "20/02/2023",
  },
  {
    id: 7,
    exerciseName: "Clean pull",
    pb: "60kg",
    sets: 5,
    reps: 1,
    equipment: "BB",
    lastActivity: "06/07/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "5",
    day: "1",
    pbDate: "20/02/2023",
  },
  {
    id: 8,
    exerciseName: "Jerk from the rack",
    pb: "60kg",
    sets: 3,
    reps: 8,
    equipment: "BB",
    lastActivity: "07/10/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "5",
    day: "2",
    pbDate: "20/02/2023",
  },
  {
    id: 9,
    exerciseName: "Snatch push press",
    pb: "60kg",
    sets: 5,
    reps: 5,
    equipment: "BB",
    lastActivity: "14/02/2023",
    category: "Weightlifting",
    bodyPart: "Upper",
    week: "5",
    day: "3",
    pbDate: "20/02/2023",
  },
];

export const ExerciseColumns = [
  { field: "exerciseName", headerName: "Exercise", width: 130 },
  { field: "pb", headerName: "PB", width: 90 },
  { field: "sets", headerName: "Sets", type: "number", width: 70 },
  { field: "reps", headerName: "Reps", type: "number", width: 70 },
  { field: "equipment", headerName: "Equipment", width: 130 },
  {
    field: "lastActivity",
    headerName: "Last Activity",
    width: 130,
  },
  {
    field: "category",
    headerName: "Category",
    width: 130,
  },
  {
    field: "bodyPart",
    headerName: "Body Part",
    width: 130,
  },
];

export const ExerciseList = [
  "Front squat",
  "Back squat",
  "Deadlift",
  "Bench press",
  "Clean and jerk",
  "Snatch balance",
  "Snatch pull",
];

export const CategoryList = ["Bodybuilding", "Weightlifting", "Conditioning"];

export const EquipmentList = ["BB", "DB", "KB"];

export const BodyPartList = [
  { title: "Upper" },
  { title: "Core" },
  { title: "Legs" },
];

export const ExerciseDetailData = [
  {
    id: 1,
    sets: 4,
    reps: 3,
    date: "20/02/2023",
    weight: 55,
    notes: "Felt heavy",
  },
  {
    id: 2,
    sets: 3,
    reps: 4,
    date: "02/03/2023",
    weight: 55,
    notes: "Missed last rep",
  },
  {
    id: 3,
    sets: 4,
    reps: 5,
    date: "05/06/2023",
    weight: 55,
    notes: "Felt good",
  },
  {
    id: 4,
    exerciseName: "Clean and jerk",
    sets: 3,
    reps: 6,
    date: "15/09/2023",
    weight: 55,
    notes: "Go heavier next time",
  },
];

export const ExerciseDetailColumns = [
  {
    field: "date",
    headerName: "Date",
    width: 130,
  },
  { field: "sets", headerName: "Sets", type: "number", width: 70 },
  { field: "reps", headerName: "Reps", type: "number", width: 70 },
  { field: "weight", headerName: "Weight (kgs)", type: "number", width: 100 },
  { field: "notes", headerName: "Notes", type: "text", width: 200 },
];
